### ISSUE TITLE
sim70x0 Direct access of CellularContext

### ISSUE THREAD

**Issue by tpecar-ltek** [FreeRTOS/FreeRTOS-Cellular-Interface-Community-Supported-Ports#4]
The CellularContext structure will change
https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface/issues/124

this will break the current sim70x0 port, but this is due to the improper direct access of module context.

`_Cellular_GetModuleContext` should have been used instead.

**Comment by chinglee-iot** [comment]
This issue is fixed in #5. Thank you for your feedback.
